name: Build APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buildozer APK
        uses: ArtemSBulgakov/buildozer-action@v1
        id: build
        with:
          command: buildozer -v android debug
          workdir: .
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cifciler-apk
          path: ${{ steps.build.outputs.releasename }}
